### ISSUE TITLE
Vulnerable to Zip Slip

### ISSUE THREAD

**Issue by Shnatsel** [quininer/unzipx#2]
[Zip Slip](https://security.snyk.io/research/zip-slip-vulnerability) is a path traversal vulnerability discovered in 2018 that affected numerous Zip implementations. 

The trick is to encode a filename starting with `../` such as `../../evil.sh`, which lets the attacker overwrite arbitrary files on the user's system - such as adding a script executed on boot, or overwriting the config file describing who can SSH into the machine.

`unzipx` uses the following code to check file paths:

https://github.com/quininer/unzipx/blob/b8d3f6c580736478ecb9a68d00a21e03246b6a0d/src/main.rs#L103-L116

This checks for absolute paths, but does not check for `../` anywhere in the path. So this implementation appears to be vulnerable to Zip Slip.

**Comment by quininer** [comment]
This is not true, see https://github.com/quininer/unzipx/blob/master/src/util.rs#L88

**Comment by Shnatsel** [comment]
I see. I'm sorry for the false alarm then! It's great to see you thought about this up front!

**Comment by quininer** [comment]
No problem, thank you for your seriousness. :)
